### ISSUE TITLE
Installation on Ledger Nano S with firmware 1.4.1

### ISSUE THREAD

**Issue by paweljacewicz** [LedgerHQ/blue-app-openpgp-card#19]
Hi!

I'd like to ask whether there will be available a release compiled for the Ledger Nano S with firmware ver. 1.4.1? I tried to compile it myself but get errors that some functions have wrong number of arguments passed to them. It seems like some changes in the Ledger SDK are responsible for it.

Thanks for any info!

**Comment by cslashm** [comment]
It should be available this Week.

Le 11 mars 2018 9:12 PM, "Paweł Jacewicz" <notifications@github.com> a
écrit :

Hi!

I'd like to ask whether there will be available a release compiled for the
Ledger Nano S with firmware ver. 1.4.1? I tried to compile it myself but
get errors that some functions have wrong number of arguments passed to
them. It seems like some changes in the Ledger SDK are responsible for it.

Thanks for any info!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LedgerHQ/blue-app-openpgp-card/issues/19>, or mute the
thread

**Comment by paweljacewicz** [comment]
Great!

Thanks for the info!

**Comment by dantrauner** [comment]
@cslashm Would anything have changed related to enabling communication with the Ledger CCID interface? I'm unable to do so post-update despite having performed the setup detailed [here](https://github.com/LedgerHQ/blue-app-openpgp-card/blob/81090d3f235a294e3f72879f4d889a3512a4e227/doc/user/blue-app-openpgp-card.rst#system-configuration) which was working for the prior FW/OpenPGP versions.

**Comment by cslashm** [comment]
done

**Comment by dantrauner** [comment]
I still seem to be getting `ERR 100696144 Operation not supported by device` – any suggestions? I'll try starting from scratch just in case now that the app is rebuilt for the latest FW (thanks btw!)

**Comment by luginbash** [comment]
me2
btw, do I really really have to re-enable SIP if am on Mac?

**Comment by dantrauner** [comment]
@luginbash yes, I'd strongly recommend keeping it on unless you have a critical use case for leaving it off and know what you're doing, as it makes it a bit harder for malicious software to establish persistence. You should only need to turn it off temporarily if you're trying to one-time modify files in `/System`, `/usr`, `/bin`, or `/sbin`.

**Comment by savenas** [comment]
Do have the latest drivers for Ledger Nano S
```system_profiler SPSmartCardsDataType
SmartCards:

    Readers:

      #01: Ledger Nano S (ATR:<3b00>)

    Reader Drivers:

      #01: org.debian.alioth.pcsclite.smartcardccid:1.4.27 (/usr/libexec/SmartCardServices/drivers/ifd-ccid.bundle)
      #02: org.debian.alioth.pcsclite.smartcardccid:1.4.30 (/usr/local/libexec/SmartCardServices/drivers/ifd-ccid.bundle)```


I made a tutorial for GPG tools, Ledger nano S and Mojave.
Please follow the link below:
https://github.com/savenas/docs/blob/master/gpg_ledger_mojave.md
